repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        args:
          [
            --fix,
            --exit-non-zero-on-fix,
            --extend-select=ANN20,
            --extend-select=ANN001,
          ]
      - id: ruff-format
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [--select=J001]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: requirements-txt-fixer
